config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'users/new'
  resource :users
  root 'sessions#index'
  get 'sessions/new'

  post 'posts/new', to: 'posts#create'
  post 'sessions/new', to: 'sessions#create'
  
  delete 'logout', to: 'sessions#destroy'

  resources :posts, only: [:new, :create, :index]
  # post 'users/new', to: 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :activation_token, :remember_token
  # before_save  email = email, only: [:create]
  #  before_save { self.email = email.downcase }
  has_many :posts
  before_create :create_activation_digest

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true
  validates :password_confirmation, presence: true

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.remember_digest = User.digest(activation_token)
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :sign_in, only: %i[new create]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.order(created_at: :desc)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Your post has been created'
      redirect_to root_path
    else
      flash[:warning] = 'Something went wrong with your post!'
    end
  end

  private

  def sign_in
    unless logged_in?
      flash[:error] = 'You must be logged in to access this section'
      redirect_to root_url # halts request cycle
      end
  end

  def post_params
    params.require(:post).permit(:title, :content, :author)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def index; end

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in(user)
      current_user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'you are logged in'
      redirect_to root_url
    else
      flash.now[:danger] = 'name or password is incorrect'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show 
  end 


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Your account has been created'
      redirect_to root_path
    else
      flash[:warning] = 'Something went wrong!'
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title)%>| memebers-only</title>
  <%= render "partials/header" %>
</head>

<body>
  <%= render "partials/navigation" %>
  <%= render "partials/flash" %>

  <%= yield %>

</body>

</html>

app/views/partials/_flash.html.erb
<% flash.each do |message_type,message| %>
<div class="alert alert-<%=message_type%>"><%=message%></div>
<%end%>

app/views/partials/_header.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">members only</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link active" href="<%= root_path%>">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="<%= posts_path %> ">posts</a>
            <% if logged_in? %>
            <!-- <%= link_to "logout", 'logout_path', {:style=>'color:#FFFFFF;', :class => "css_class"} %> -->
            <%=  link_to "log out" ,logout_path,  method: :delete  %>
            <a class="nav-item nav-link active" href="<%= new_post_path %>">Create post <span
                    class="sr-only">(current)</span></a>
            <% else %>
            <a class="nav-item nav-link" href="<%= sessions_new_path %>">login</a>
            <% end %>

        </div>
    </div>
</nav>

app/views/posts/index.html.erb
<div class="all-post text-center">

  <h1> All Posts</h1>
</div>


<% @posts.each_slice(2) do |c| %>

<div class="main d-flex justify-content-center">

  <div class="box-post justify-content-left backbox">

    <h3><%= c[0].title %></h3>
    <p><%= c[0].content %><p>
        <% if logged_in? %>
        <strong><%= User.find(c[0].user_id).name %> </strong>
        <% end %>

  </div>


  <div class="box-post justify-content-left backbox">
    <% if !c[1].nil? %>
    <h3><%= c[1].title %></h3>
    <p><%= c[1].content %><p>
        <% if logged_in?  %>
        <strong><%= User.find(c[1].user_id ).name %> </strong>
        <% end %>

  </div>
  <%end%>
</div>

<% end %>

app/views/posts/new.html.erb
<%= provide(:title,'upload content') %>
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>

        <div class="col-sm-4 login-wrap">
            <h2>Create Article</h2>
            <%= form_for(@post, url:  new_post_path ) do |f| %>

            <%= f.label :title, "Title" %> <br>
            <%= f.text_field :title , class: "form-control" %> <br>

            <%= f.label :content, "Content" %> <br>
            <%= f.text_area :content , class: "form-control" %> <br>

            <%= f.hidden_field :user_id %>


            <%= f.submit %> <br>


            <% end %>
        </div>

        <div class="col-sm-4"></div>
    </div>
</div>

app/views/users/new.html.erb
<%= provide(:title,'login') %>
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>

        <div class="col-sm-4 login-wrap">
            <h2>sign up</h2>
            
            <%= form_for(@user , url: users_path) do |f| %>

            <%= f.label :name, "name" %> <br>
            <%= f.text_field :name , class: "form-control" %> <br>
            <%= f.label :email, "email" %> <br>
            <%= f.email_field :email , class: "form-control" %> <br>

            <%= f.label :password, "password" %> <br>
            <%= f.password_field :password , class: "form-control"  %> <br>


            <%= f.label :password, "confirmation" %> <br>
            <%= f.password_field :password_confirmation , class: "form-control"  %> <br>
            <%= f.submit  "SIGN UP" %><br>
            <span>already a member? <%= link_to "login" , sessions_new_path %></span>
            <% end %>
        </div>

        <div class="col-sm-4"></div>
    </div>
</div>